name: Finnets-App-Database
services:
  mock_bank_database:
    build: ./mock_bank_database
    container_name: mock_bank_database
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bank_shared_net

volumes:
  db_data:
networks:
  bank_shared_net:
    external: true
    name: bank_shared_net
